[workspace]
resolver = "2"
members = [
    "raydeon",
    "pyraydeon",
]

[workspace.dependencies]
raydeon = { path = "./raydeon", version = "0.2" }
pyrayeon = { path = "./pyraydeon", version = "0.1.0-alpha" }

anyhow = "1"
bon = "3"
cgmath = "0.17"
collision = "0.20"
dot_vox = "5"
env_logger = "0.11"
euclid = "0.22"
float-cmp = "0.5"
log = "0.4"
pyo3 = "0.22"
rand = "0.8"
rayon = "1.2"
numpy = "0.22"
svg = "0.18"
tracing = "0.1"
