[package]
name = "raydeon"
version = "0.1.0"
authors = ["cbgbt <cbgbt@cabbage.bot>"]
edition = "2018"

[dependencies]
cgmath = "0.18"
collision = "0.20"
euclid = "0.20"
rayon = "1.2"

[dev-dependencies]
float-cmp = "0.5"
