[package]
name = "raydeon"
version = "0.2.0"
authors = ["cbgbt <cbgbt@cabbage.bot>"]
edition = "2021"

[dependencies]
bon.workspace = true
euclid.workspace = true
float-cmp.workspace = true
nutype.workspace = true
rayon.workspace = true
snafu.workspace = true
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
dot_vox.workspace = true
env_logger.workspace = true
proptest.workspace = true
svg.workspace = true
test-case.workspace = true
