[package]
name = "raydeon"
version = "0.2.0"
authors = ["cbgbt <cbgbt@cabbage.bot>"]
edition = "2021"

[dependencies]
bon.workspace = true
cgmath.workspace = true
collision.workspace = true
dot_vox.workspace = true
euclid.workspace = true
float-cmp.workspace = true
log.workspace = true
rand = { workspace = true, features = ["std_rng"] }
rayon.workspace = true
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
env_logger.workspace = true
svg.workspace = true
